packages:
  - "packages/*"
allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@radiant-core/radiantjs@2.0.0'
  - '@radiant-core/radiantjs@2.0.1'
  - '@radiant-core/radiantjs@2.0.2'
  - '@radiant-core/radiantjs@2.0.3'
  - '@radiant-core/radiantjs@2.0.5'
overrides:
  protobufjs: ^7.5.5
