import { describe, it, expect } from "vitest";
import {
  buildEpochDaaBytecode,
  buildLinearDaaBytecode,
  dMintScript,
  dMintDiffToTarget,
  pushMinimal,
  EPOCH_MAX_SAFE_TARGET,
} from "../script";

/**
 * Regression tests for the dMint DAA int64-overflow fix (EPOCH + LWMA).
 *
 * Radiant script numbers are 64-bit (`CScriptNum`); `OP_MUL` ABORTS the script
 * with a number-range error when the product leaves int64 (radiant-core
 * `interpreter.cpp`: `OP_MUL → safeMul`, on overflow `set_error(...,
 * SCRIPT_ERR_INVALID_NUMBER_RANGE_64_BIT)`). The wallet computes the retarget
 * off-chain with BigInt (no overflow) and never sees the abort, so the covenant
 * has to keep the on-chain multiply inside int64 itself — an off-chain deploy
 * check is not enough.
 *
 * The proof here does NOT depend on a JS interpreter's fidelity: it models the
 * exact ops the bytecode performs under int64 semantics (`safeMul` throws on
 * overflow, exactly like radiant-core) and shows the OLD formulas overflow while
 * the shipped ones never do, then asserts the generated bytecode implements the
 * proven-safe formulas.
 */

// radiant-core MAX_TARGET (= the script's PUSH_MAX_TARGET, not exported here).
const MAX_TARGET = (1n << 63n) - 1n;
const INT64_MAX = (1n << 63n) - 1n;
const INT64_MIN = -(1n << 63n);

/** Models Radiant `OP_MUL`: aborts when the product leaves int64. */
function safeMul(a: bigint, b: bigint): bigint {
  const r = a * b;
  if (r > INT64_MAX || r < INT64_MIN) {
    throw new Error("INT64_OVERFLOW");
  }
  return r;
}
const min = (a: bigint, b: bigint) => (a < b ? a : b);
const max = (a: bigint, b: bigint) => (a > b ? a : b);

// EPOCH clampedDelta = max(targetTime >> N, min(targetTime << N, delta)) — always
// positive and ≤ targetTime << N, so EPOCH's overflow is purely magnitude.
function clampDelta(delta: bigint, targetTime: bigint, N: number): bigint {
  const up = targetTime << BigInt(N);
  const lo = targetTime >> BigInt(N);
  return max(lo, min(up, delta));
}

// Both EPOCH paths finish with the bytecode's ≥1 clamp (OP_DUP OP_1 OP_LESSTHAN
// IF DROP OP_1), so the stored target is always ≥ 1.
const atLeast1 = (t: bigint) => max(1n, t);

// OLD EPOCH bytecode: newTarget = max(1, min(MAX_TARGET, (target × clampedDelta) / targetTime)).
// Multiply-first, and the output is capped at MAX_TARGET (2^63), NOT 2^48 — so
// target drifts up over slow epochs and the multiply eventually overflows.
function epochOld(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  N: number
) {
  const cd = clampDelta(delta, targetTime, N);
  return atLeast1(min(MAX_TARGET, safeMul(target, cd) / targetTime));
}

// SHIPPED EPOCH bytecode: tc = min(target, 2^48);
// newTarget = max(1, min(2^48, (tc / targetTime) × clampedDelta)). Divide-first +
// a 2^48 clamp on BOTH sides keeps the multiply ≤ 2^52 for any reachable state.
function epochNew(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  N: number
) {
  const cd = clampDelta(delta, targetTime, N);
  const tc = min(target, EPOCH_MAX_SAFE_TARGET);
  return atLeast1(min(EPOCH_MAX_SAFE_TARGET, safeMul(tc / targetTime, cd)));
}

// LWMA models: target pre-capped to MAX_TARGET/4, divide-first. The difference is
// only the timeDelta floor.
const QUARTER_MAX = MAX_TARGET / 4n;
function lwmaTimeDeltaOld(delta: bigint, targetTime: bigint): bigint {
  return min(4n * targetTime, delta); // upper cap only — negative passes through
}
function lwmaTimeDeltaNew(delta: bigint, targetTime: bigint): bigint {
  return max(0n, min(4n * targetTime, delta)); // + floor at 0
}
function lwma(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  floor: boolean
) {
  const tc = min(target, QUARTER_MAX);
  const td = floor
    ? lwmaTimeDeltaNew(delta, targetTime)
    : lwmaTimeDeltaOld(delta, targetTime);
  return max(1n, min(MAX_TARGET, safeMul(tc / targetTime, td)));
}

// ASERT model: drift-based exponential retargeting
// Entry stack: [target, lastTime, targetTime, ...]
// Formula: drift = (currentTime - lastTime - targetTime) / halfLife
//          drift clamped to [-4, +4]
//          target = target << drift (positive drift = easier, negative = harder)
function asert(
  target: bigint,
  currentTime: bigint,
  lastTime: bigint,
  targetTime: bigint,
  halfLife: bigint
) {
  const timeDelta = currentTime - lastTime;
  const excess = timeDelta - targetTime;
  let drift = excess / halfLife;
  // Clamp drift to [-4, +4]
  drift = max(-4n, min(4n, drift));
  // Apply shift: positive drift = multiply (easier), negative = divide (harder)
  let result = target;
  if (drift > 0n) {
    // Make easier: target *= 2^drift (but cap at MAX_TARGET)
    for (let i = 0n; i < drift; i++) {
      if (result > MAX_TARGET / 2n) {
        result = MAX_TARGET;
        break;
      }
      result = result * 2n;
    }
  } else if (drift < 0n) {
    // Make harder: target /= 2^|drift|
    const halvings = -drift;
    for (let i = 0n; i < halvings; i++) {
      result = result / 2n;
    }
  }
  // Clamp to minimum 1
  return max(1n, result);
}

describe("dMint DAA int64-overflow fix", () => {
  describe("EPOCH — target × clampedDelta overflow", () => {
    it("OLD bytecode overflows int64 at deploy when targetTime ≥ 2048 (target = 2^48, N=4)", () => {
      const target = EPOCH_MAX_SAFE_TARGET; // 2^48, the deploy ceiling
      const targetTime = 2048n;
      const hugeDelta = targetTime << 4n; // a slow epoch hits the upper clamp
      expect(() => epochOld(target, hugeDelta, targetTime, 4)).toThrow(
        "INT64_OVERFLOW"
      );
      // Shipped formula is safe at the same inputs.
      const t = epochNew(target, hugeDelta, targetTime, 4);
      expect(t).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
      expect(t).toBeGreaterThanOrEqual(1n);
    });

    it("OLD bytecode bricks within a few slow epochs even for small targetTime (output capped at MAX_TARGET, not 2^48)", () => {
      const targetTime = 600n;
      const N = 4;
      const slow = targetTime << BigInt(N); // sustained slow blocks
      // SHIPPED: target stays ≤ 2^48 forever — never overflows.
      let nt = EPOCH_MAX_SAFE_TARGET;
      for (let i = 0; i < 50; i++) {
        nt = epochNew(nt, slow, targetTime, N);
        expect(nt).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
      }
      // OLD: target drifts up past 2^48 (output cap is MAX_TARGET) and the
      // multiply overflows within a handful of epochs.
      let ot = EPOCH_MAX_SAFE_TARGET;
      let bricked = false;
      try {
        for (let i = 0; i < 50; i++) ot = epochOld(ot, slow, targetTime, N);
      } catch (e) {
        bricked = (e as Error).message === "INT64_OVERFLOW";
      }
      expect(bricked).toBe(true);
    });

    it("SHIPPED EPOCH never overflows across a boundary-input sweep", () => {
      const targets = [
        1n,
        1n << 30n,
        1n << 40n,
        EPOCH_MAX_SAFE_TARGET - 1n,
        EPOCH_MAX_SAFE_TARGET,
      ];
      const targetTimes = [1n, 2n, 60n, 600n, 2047n, 2048n, 86400n];
      const deltas = [-1_000_000n, -1n, 0n, 1n, 1n << 40n];
      const Ns = [1, 2, 3, 4];
      for (const tgt of targets)
        for (const tt of targetTimes)
          for (const d of deltas)
            for (const N of Ns) {
              const out = epochNew(tgt, d, tt, N); // must not throw
              expect(out).toBeGreaterThanOrEqual(1n);
              expect(out).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
            }
    });
  });

  describe("LWMA — negative timeDelta overflow", () => {
    it("OLD bytecode overflows on a backwards-clock block; SHIPPED floors at 0", () => {
      const target = QUARTER_MAX; // difficulty floor 4 → largest target
      const targetTime = 60n;
      const backwards = -300n; // mint locktime earlier than the previous mint
      expect(() => lwma(target, backwards, targetTime, false)).toThrow(
        "INT64_OVERFLOW"
      );
      // Floored: no overflow; a backwards delta yields product 0 → the ≥1 clamp
      // in the bytecode maps it to target 1 (max difficulty for that block).
      const out = lwma(target, backwards, targetTime, true);
      expect(out).toBe(1n);
    });

    it("SHIPPED LWMA never overflows across a sweep incl. large negative deltas", () => {
      const targets = [1n, 1n << 40n, QUARTER_MAX];
      const targetTimes = [1n, 60n, 600n];
      const deltas = [-(1n << 50n), -300n, 0n, 1n, 1n << 50n];
      for (const tgt of targets)
        for (const tt of targetTimes)
          for (const d of deltas) {
            const out = lwma(tgt, d, tt, true);
            expect(out).toBeGreaterThanOrEqual(0n);
          }
    });
  });

  describe("generated bytecode implements the safe formulas", () => {
    it("EPOCH bytecode is divide-first and clamps target to 2^48 on both sides", () => {
      const hex = buildEpochDaaBytecode(2016, 4);
      const push2_48 = pushMinimal(EPOCH_MAX_SAFE_TARGET); // 0700000000000001
      // 2^48 clamp appears on both sides of the multiply.
      const occurrences = hex.split(push2_48).length - 1;
      expect(occurrences).toBe(2);
      // The old MAX_TARGET output cap (08ffffffffffffff7f) is gone from EPOCH.
      expect(hex).not.toContain("08ffffffffffffff7f");
      // Divide-first: OP_DIV (96) precedes the retarget OP_MUL (95) in the
      // newTarget region (… 96 95 <push2^48> a3).
      expect(hex).toContain(`96` + `95` + push2_48 + `a3`);
    });

    it("LWMA bytecode floors timeDelta at 0 after the upper cap (… a3 00 a4 …)", () => {
      const hex = buildLinearDaaBytecode();
      expect(hex).toContain("a300a4"); // OP_MIN, OP_0, OP_MAX
    });
  });

  describe("ASERT — fast blocks should increase difficulty", () => {
    it("ASERT model: fast blocks (10s vs 60s target) should decrease target/increase difficulty", () => {
      // Simulate the ASERT token scenario:
      // - Deploy target: MAX_TARGET/2 (difficulty 2)
      // - Target block time: 60s
      // - Half life: 1000
      // - Actual block time: 10s (much faster)
      
      const deployTarget = MAX_TARGET / 2n; // difficulty 2
      const targetTime = 60n;
      const halfLife = 1000n;
      
      // Simulate 10 blocks coming at 10s intervals (60s apart in absolute time)
      let currentTarget = deployTarget;
      let lastTime = 0n;
      
      for (let i = 0; i < 10; i++) {
        const currentTime = lastTime + 10n; // 10s block time
        currentTarget = asert(currentTarget, currentTime, lastTime, targetTime, halfLife);
        lastTime = currentTime;
      }
      
      // After 10 fast blocks, difficulty should have increased significantly
      // Starting difficulty: 2
      // Each block: drift = (10-60)/1000 = -0.05, so |drift| ≈ 0 (clamped), no change
      // Wait - with 10s blocks and 60s target, drift = -0.05 which rounds to 0
      // So no retargeting happens immediately...
      
      // Actually let me check - does drift accumulate?
      // No, each mint is independent based on lastTime
      
      // The issue is: with consistent 10s blocks and halfLife=1000,
      // drift = -0.05 which is between 0 and -1, so it rounds to 0
      // ASERT requires drift magnitude >= 1 to trigger any shift
      
      // For significant retargeting, we need more extreme conditions
      // Let's test with 5s block time
      let fastTarget = MAX_TARGET / 2n;
      lastTime = 0n;
      for (let i = 0; i < 10; i++) {
        const currentTime = lastTime + 5n; // 5s block time
        fastTarget = asert(fastTarget, currentTime, lastTime, targetTime, halfLife);
        lastTime = currentTime;
      }
      
      // After 10 blocks at 5s each:
      // drift = (5-60)/1000 = -0.055 → still rounds to 0
      // No retargeting!
      
      // This suggests the halfLife might be too high for the actual block rate
      // Or we need sustained fast blocks over many more iterations
      
      // Let's try with 0.5s block time (extreme)
      let extremeTarget = MAX_TARGET / 2n;
      lastTime = 0n;
      for (let i = 0; i < 10; i++) {
        const currentTime = lastTime + 1n; // 1s block time
        extremeTarget = asert(extremeTarget, currentTime, lastTime, targetTime, halfLife);
        lastTime = currentTime;
      }
      
      // drift = (1-60)/1000 = -0.059 → still rounds to 0!
      // This is a problem - with halfLife=1000 and 60s target,
      // you need (blockTime - 60) / 1000 to be <= -1
      // So blockTime needs to be <= -940, which is impossible
      
      // Actually wait - I think I misread. The formula is:
      // drift = (timeDelta - targetTime) / halfLife
      // timeDelta = currentTime - lastTime (time between blocks)
      // For 10s blocks: timeDelta = 10, excess = 10-60 = -50, drift = -0.05
      
      // But the CLAMP is to [-4, +4], so -0.05 stays as -0.05
      // Then the bytecode does: drift = int(drift) ? Or does it use the value?
      
      // Let me re-read the bytecode...
      // The bytecode checks "DUP 0 GT" and "DUP 0 LT", so it's checking if drift > 0 or < 0
      // With drift = -0.05, 0 LT is TRUE, so it goes into the negative branch
      // But then it does NEGATE and 2DIV loop
      
      // Wait, -0.05 is between 0 and -1. When we NEGATE: 0.05
      // Then "DUP 0 GT" → TRUE, so we do the halving
      // But with drift = -0.05, we'd do... less than 1 halving?
      
      // I think the issue is drift needs to be INTEGER for the loop
      // Let me check if the bytecode does int conversion...
      
      // Actually looking at the bytecode, it does integer comparisons
      // But script numbers are integers, so -0.05 becomes 0?
      
      // If drift = 0 (truncated), then:
      // - DUP 0 GT → FALSE (0 is not > 0)
      // - DUP 0 LT → FALSE (0 is not < 0)
      // - Falls through to DROP drift (no change)
      
      // THIS IS THE BUG!
      // With halfLife=1000 and targetTime=60, you need:
      // (blockTime - 60) / 1000 <= -1 for retargeting
      // blockTime <= -940 (impossible)
      
      // OR the bytecode needs to handle fractional drift differently
      
      expect(extremeTarget).toBeLessThan(MAX_TARGET / 2n); // Should have decreased
    });
    
    it("ASERT with halfLife=100 requires much faster retargeting", () => {
      const deployTarget = MAX_TARGET / 2n;
      const targetTime = 60n;
      const halfLife = 100n; // Much shorter
      
      let currentTarget = deployTarget;
      let lastTime = 0n;
      
      // Simulate 10s block times
      for (let i = 0; i < 100; i++) {
        const currentTime = lastTime + 10n;
        currentTarget = asert(currentTarget, currentTime, lastTime, targetTime, halfLife);
        lastTime = currentTime;
      }
      
      // drift = (10-60)/100 = -0.5 → still 0 in integer math
      // Need more extreme or shorter halfLife
      
      // Try with 1s blocks and halfLife=10
      const shortHalfLife = 10n;
      currentTarget = deployTarget;
      lastTime = 0n;
      
      for (let i = 0; i < 50; i++) {
        const currentTime = lastTime + 1n; // 1s blocks
        currentTarget = asert(currentTarget, currentTime, lastTime, targetTime, shortHalfLife);
        lastTime = currentTime;
      }
      
      // drift = (1-60)/10 = -5.9 → clamped to -4
      // 4 halvings: MAX_TARGET/2 → MAX_TARGET/32 (difficulty 32)
      expect(currentTarget).toBeLessThanOrEqual(MAX_TARGET / 16n);
    });
  });

  describe("EPOCH deploy validation (wires up EPOCH_MAX_SAFE_TARGET)", () => {
    const cref = "11".repeat(36);
    const tref = "22".repeat(36);
    it("rejects an EPOCH deploy whose initial target exceeds 2^48 (difficulty < 32768)", () => {
      expect(() =>
        dMintScript(
          0,
          cref,
          tref,
          100,
          10,
          dMintDiffToTarget(10), // target ≈ 2^59 > 2^48
          "sha256d",
          "epoch",
          { epochLength: 10, maxAdjustment: 2 } as never,
          1700000000
        )
      ).toThrow(/EPOCH_MAX_SAFE_TARGET|2\^48|32768/);
    });

    it("accepts an EPOCH deploy at difficulty 32768 (target = 2^48)", () => {
      expect(() =>
        dMintScript(
          0,
          cref,
          tref,
          100,
          10,
          dMintDiffToTarget(32768),
          "sha256d",
          "epoch",
          { epochLength: 10, maxAdjustment: 2 } as never,
          1700000000
        )
      ).not.toThrow();
    });
  });

  describe("LWMA deploy validation (wires up MAX_TARGET/4 cap)", () => {
    const cref = "11".repeat(36);
    const tref = "22".repeat(36);
    it("rejects a LWMA deploy whose initial target exceeds MAX_TARGET/4 (difficulty < 4)", () => {
      expect(() =>
        dMintScript(
          0,
          cref,
          tref,
          100,
          10,
          dMintDiffToTarget(2), // target = MAX_TARGET/2 > MAX_TARGET/4
          "sha256d",
          "lwma",
          {} as never,
          1700000000
        )
      ).toThrow(/MAX_TARGET\/4|difficulty ≥ 4/);
    });

    it("accepts a LWMA deploy at difficulty 4 (target = MAX_TARGET/4)", () => {
      expect(() =>
        dMintScript(
          0,
          cref,
          tref,
          100,
          10,
          dMintDiffToTarget(4),
          "sha256d",
          "lwma",
          {} as never,
          1700000000
        )
      ).not.toThrow();
    });
  });
});
