import { describe, it, expect } from "vitest";
import {
  buildAsertDaaBytecode,
  buildEpochDaaBytecode,
  buildLinearDaaBytecode,
  dMintScript,
  dMintDiffToTarget,
  pushMinimal,
  EPOCH_MAX_SAFE_TARGET,
} from "../script";

/**
 * Regression tests for the dMint DAA int64-overflow fix (EPOCH + LWMA).
 *
 * Radiant script numbers are 64-bit (`CScriptNum`); `OP_MUL` ABORTS the script
 * with a number-range error when the product leaves int64 (radiant-core
 * `interpreter.cpp`: `OP_MUL → safeMul`, on overflow `set_error(...,
 * SCRIPT_ERR_INVALID_NUMBER_RANGE_64_BIT)`). The wallet computes the retarget
 * off-chain with BigInt (no overflow) and never sees the abort, so the covenant
 * has to keep the on-chain multiply inside int64 itself — an off-chain deploy
 * check is not enough.
 *
 * The proof here does NOT depend on a JS interpreter's fidelity: it models the
 * exact ops the bytecode performs under int64 semantics (`safeMul` throws on
 * overflow, exactly like radiant-core) and shows the OLD formulas overflow while
 * the shipped ones never do, then asserts the generated bytecode implements the
 * proven-safe formulas.
 */

// radiant-core MAX_TARGET (= the script's PUSH_MAX_TARGET, not exported here).
const MAX_TARGET = (1n << 63n) - 1n;
const INT64_MAX = (1n << 63n) - 1n;
const INT64_MIN = -(1n << 63n);

/** Models Radiant `OP_MUL`: aborts when the product leaves int64. */
function safeMul(a: bigint, b: bigint): bigint {
  const r = a * b;
  if (r > INT64_MAX || r < INT64_MIN) {
    throw new Error("INT64_OVERFLOW");
  }
  return r;
}
const min = (a: bigint, b: bigint) => (a < b ? a : b);
const max = (a: bigint, b: bigint) => (a > b ? a : b);

// EPOCH clampedDelta = max(targetTime >> N, min(targetTime << N, delta)) — always
// positive and ≤ targetTime << N, so EPOCH's overflow is purely magnitude.
function clampDelta(delta: bigint, targetTime: bigint, N: number): bigint {
  const up = targetTime << BigInt(N);
  const lo = targetTime >> BigInt(N);
  return max(lo, min(up, delta));
}

// Both EPOCH paths finish with the bytecode's ≥1 clamp (OP_DUP OP_1 OP_LESSTHAN
// IF DROP OP_1), so the stored target is always ≥ 1.
const atLeast1 = (t: bigint) => max(1n, t);

// OLD EPOCH bytecode: newTarget = max(1, min(MAX_TARGET, (target × clampedDelta) / targetTime)).
// Multiply-first, and the output is capped at MAX_TARGET (2^63), NOT 2^48 — so
// target drifts up over slow epochs and the multiply eventually overflows.
function epochOld(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  N: number
) {
  const cd = clampDelta(delta, targetTime, N);
  return atLeast1(min(MAX_TARGET, safeMul(target, cd) / targetTime));
}

// SHIPPED EPOCH bytecode: tc = min(target, 2^48);
// newTarget = max(1, min(2^48, (tc / targetTime) × clampedDelta)). Divide-first +
// a 2^48 clamp on BOTH sides keeps the multiply ≤ 2^52 for any reachable state.
function epochNew(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  N: number
) {
  const cd = clampDelta(delta, targetTime, N);
  const tc = min(target, EPOCH_MAX_SAFE_TARGET);
  return atLeast1(min(EPOCH_MAX_SAFE_TARGET, safeMul(tc / targetTime, cd)));
}

// LWMA models: target pre-capped to MAX_TARGET/4, divide-first. The difference is
// only the timeDelta floor.
const QUARTER_MAX = MAX_TARGET / 4n;
function lwmaTimeDeltaOld(delta: bigint, targetTime: bigint): bigint {
  return min(4n * targetTime, delta); // upper cap only — negative passes through
}
function lwmaTimeDeltaNew(delta: bigint, targetTime: bigint): bigint {
  return max(0n, min(4n * targetTime, delta)); // + floor at 0
}
function lwma(
  target: bigint,
  delta: bigint,
  targetTime: bigint,
  floor: boolean
) {
  const tc = min(target, QUARTER_MAX);
  const td = floor
    ? lwmaTimeDeltaNew(delta, targetTime)
    : lwmaTimeDeltaOld(delta, targetTime);
  return max(1n, min(MAX_TARGET, safeMul(tc / targetTime, td)));
}


describe("dMint DAA int64-overflow fix", () => {
  describe("EPOCH — target × clampedDelta overflow", () => {
    it("OLD bytecode overflows int64 at deploy when targetTime ≥ 2048 (target = 2^48, N=4)", () => {
      const target = EPOCH_MAX_SAFE_TARGET; // 2^48, the deploy ceiling
      const targetTime = 2048n;
      const hugeDelta = targetTime << 4n; // a slow epoch hits the upper clamp
      expect(() => epochOld(target, hugeDelta, targetTime, 4)).toThrow(
        "INT64_OVERFLOW"
      );
      // Shipped formula is safe at the same inputs.
      const t = epochNew(target, hugeDelta, targetTime, 4);
      expect(t).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
      expect(t).toBeGreaterThanOrEqual(1n);
    });

    it("OLD bytecode bricks within a few slow epochs even for small targetTime (output capped at MAX_TARGET, not 2^48)", () => {
      const targetTime = 600n;
      const N = 4;
      const slow = targetTime << BigInt(N); // sustained slow blocks
      // SHIPPED: target stays ≤ 2^48 forever — never overflows.
      let nt = EPOCH_MAX_SAFE_TARGET;
      for (let i = 0; i < 50; i++) {
        nt = epochNew(nt, slow, targetTime, N);
        expect(nt).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
      }
      // OLD: target drifts up past 2^48 (output cap is MAX_TARGET) and the
      // multiply overflows within a handful of epochs.
      let ot = EPOCH_MAX_SAFE_TARGET;
      let bricked = false;
      try {
        for (let i = 0; i < 50; i++) ot = epochOld(ot, slow, targetTime, N);
      } catch (e) {
        bricked = (e as Error).message === "INT64_OVERFLOW";
      }
      expect(bricked).toBe(true);
    });

    it("SHIPPED EPOCH never overflows across a boundary-input sweep", () => {
      const targets = [
        1n,
        1n << 30n,
        1n << 40n,
        EPOCH_MAX_SAFE_TARGET - 1n,
        EPOCH_MAX_SAFE_TARGET,
      ];
      const targetTimes = [1n, 2n, 60n, 600n, 2047n, 2048n, 86400n];
      const deltas = [-1_000_000n, -1n, 0n, 1n, 1n << 40n];
      const Ns = [1, 2, 3, 4];
      for (const tgt of targets)
        for (const tt of targetTimes)
          for (const d of deltas)
            for (const N of Ns) {
              const out = epochNew(tgt, d, tt, N); // must not throw
              expect(out).toBeGreaterThanOrEqual(1n);
              expect(out).toBeLessThanOrEqual(EPOCH_MAX_SAFE_TARGET);
            }
    });
  });

  describe("LWMA — negative timeDelta overflow", () => {
    it("OLD bytecode overflows on a backwards-clock block; SHIPPED floors at 0", () => {
      const target = QUARTER_MAX; // difficulty floor 4 → largest target
      const targetTime = 60n;
      const backwards = -300n; // mint locktime earlier than the previous mint
      expect(() => lwma(target, backwards, targetTime, false)).toThrow(
        "INT64_OVERFLOW"
      );
      // Floored: no overflow; a backwards delta yields product 0 → the ≥1 clamp
      // in the bytecode maps it to target 1 (max difficulty for that block).
      const out = lwma(target, backwards, targetTime, true);
      expect(out).toBe(1n);
    });

    it("SHIPPED LWMA never overflows across a sweep incl. large negative deltas", () => {
      const targets = [1n, 1n << 40n, QUARTER_MAX];
      const targetTimes = [1n, 60n, 600n];
      const deltas = [-(1n << 50n), -300n, 0n, 1n, 1n << 50n];
      for (const tgt of targets)
        for (const tt of targetTimes)
          for (const d of deltas) {
            const out = lwma(tgt, d, tt, true);
            expect(out).toBeGreaterThanOrEqual(0n);
          }
    });
  });

  describe("generated bytecode implements the safe formulas", () => {
    it("EPOCH bytecode is divide-first and clamps target to 2^48 on both sides", () => {
      const hex = buildEpochDaaBytecode(2016, 4);
      const push2_48 = pushMinimal(EPOCH_MAX_SAFE_TARGET); // 0700000000000001
      // 2^48 clamp appears on both sides of the multiply.
      const occurrences = hex.split(push2_48).length - 1;
      expect(occurrences).toBe(2);
      // The old MAX_TARGET output cap (08ffffffffffffff7f) is gone from EPOCH.
      expect(hex).not.toContain("08ffffffffffffff7f");
      // Divide-first: OP_DIV (96) precedes the retarget OP_MUL (95) in the
      // newTarget region (… 96 95 <push2^48> a3).
      expect(hex).toContain(`96` + `95` + push2_48 + `a3`);
    });

    it("LWMA bytecode floors timeDelta at 0 after the upper cap (… a3 00 a4 …)", () => {
      const hex = buildLinearDaaBytecode();
      expect(hex).toContain("a300a4"); // OP_MIN, OP_0, OP_MAX
    });
  });

  describe("ASERT-v2 — fractional fixed-point retarget", () => {
    // Behavioural + full bytecode↔reference parity coverage live in
    // dmint-asert-v2.test.ts and dmint-asert-v2-bytecode.test.ts. Here we pin the
    // on-chain bytecode SHAPE the miner's old-vs-new ASERT detection relies on.
    it("emits the v2 signature (<RADIX push> OP_MUL … OP_DIV), not the legacy stepper", () => {
      const hex = buildAsertDaaBytecode(60);
      // common prefix, then RADIX push (65536 = "03000001") + OP_MUL ("95")
      expect(hex).toContain("c5527994537994" + "03000001" + "95");
      // legacy power-of-2 markers must be gone
      expect(hex).not.toContain("7654a0"); // old DUP 4 GT drift clamp
      expect(hex).not.toContain("76548f"); // old DUP 4 NEGATE
    });

    it("rejects halfLife < 1 at build time (would divide by zero on-chain)", () => {
      expect(() => buildAsertDaaBytecode(0)).toThrow();
    });
  });
});
